### ISSUE TITLE
Fix install tests for windows

### ISSUE THREAD

**Issue by marianavillarp** [ibm-messaging/mq-ansible#60]
Currently our testing framework on Windows fails as shown in #58:

> tests have broken for windows as become:true tries to run as sudo which returns error ```The powershell shell family is incompatible with the sudo become plugin```
> To fix this playbooks should have `become: false` but not sure if this will break tests on unix based platforms.
> Playbooks now can be run, however roles can't due to `The field 'environment' has an invalid value, which includes an undefined variable. The error was: 'dict object' has no attribute 'PATH' error.` Not sure yet why this is happening?
